import type { GameDefinition } from "../types";

export const gameRegistry: GameDefinition[] = [
  {
    id: "academy-plaza",
    worldId: "hub",
    titleKey: "academy.game.plaza",
    learningGoals: ["spatial_navigation", "choice_agency"],
    cognitiveSkills: ["spatial_reasoning", "decision_making", "attention"],
    ageRange: [4, 10],
    fallbackMode: "responsive-html",
  },
  {
    id: "citrus-quality-sort",
    worldId: "citrus",
    titleKey: "academy.game.citrus",
    learningGoals: ["classification", "observation", "scientific_reasoning"],
    cognitiveSkills: ["classification", "problem_solving", "attention"],
    ageRange: [4, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "pixel-path",
    worldId: "logic",
    titleKey: "academy.game.logic",
    learningGoals: ["pre_coding", "strategy"],
    cognitiveSkills: ["pre_coding", "sequencing", "strategy", "problem_solving"],
    ageRange: [5, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "anatomy-friendly-explorer",
    worldId: "anatomy",
    titleKey: "academy.game.anatomy",
    learningGoals: ["body_awareness", "spatial_recognition"],
    cognitiveSkills: ["cause_effect", "classification", "attention"],
    ageRange: [5, 10],
    fallbackMode: "asset-slot",
  },
  {
    id: "science-garden-grow",
    worldId: "science",
    titleKey: "academy.game.science",
    learningGoals: ["cause_effect", "observation"],
    cognitiveSkills: ["cause_effect", "sequencing", "creativity"],
    ageRange: [4, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "animal-habitat-sort",
    worldId: "animals",
    titleKey: "academy.game.animals",
    learningGoals: ["classification", "observation"],
    cognitiveSkills: ["classification", "decision_making"],
    ageRange: [4, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "rhythm-fruit-stage",
    worldId: "music",
    titleKey: "academy.game.music",
    learningGoals: ["listening", "pattern_recognition"],
    cognitiveSkills: ["working_memory", "pattern_recognition", "attention"],
    ageRange: [4, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "feelings-empathy",
    worldId: "feelings",
    titleKey: "academy.game.feelings",
    learningGoals: ["emotional_reasoning", "decision_making"],
    cognitiveSkills: ["emotional_reasoning", "decision_making"],
    ageRange: [4, 10],
    fallbackMode: "webgl-scene",
  },
  {
    id: "language-constellation",
    worldId: "language",
    titleKey: "academy.game.language",
    learningGoals: ["phonics", "vocabulary", "listening"],
    cognitiveSkills: ["sequencing", "working_memory", "attention"],
    ageRange: [5, 10],
    fallbackMode: "asset-slot",
  },
  {
    id: "finale-locks",
    worldId: "finale",
    titleKey: "academy.game.finale",
    learningGoals: ["problem_solving", "strategy"],
    cognitiveSkills: ["problem_solving", "strategy", "working_memory"],
    ageRange: [5, 10],
    fallbackMode: "webgl-scene",
  },
];
